from __future__ import annotations

from app.services.errors import NotFoundError
from app.services.models import GitLabMergeRequest, GitLabPerson, GitLabTarget

people = {
    "ava": GitLabPerson(id=1, name="Ava Chen", username="avachen"),
    "noah": GitLabPerson(id=2, name="Noah Patel", username="npatel"),
    "lena": GitLabPerson(id=3, name="Lena Ortiz", username="lortiz"),
    "marcus": GitLabPerson(id=4, name="Marcus Reid", username="mreid"),
    "iris": GitLabPerson(id=5, name="Iris Singh", username="isingh"),
    "jude": GitLabPerson(id=6, name="Jude Walker", username="jwalker"),
}

fixture_targets: dict[tuple[str, str], GitLabTarget] = {
    ("project", "1042"): GitLabTarget(
        id="1042",
        type="project",
        name="Payments Platform",
        path="platform/payments",
        web_url="https://gitlab.example.com/platform/payments",
    ),
    ("project", "2044"): GitLabTarget(
        id="2044",
        type="project",
        name="Identity",
        path="platform/identity",
        web_url="https://gitlab.example.com/platform/identity",
    ),
    ("project", "3055"): GitLabTarget(
        id="3055",
        type="project",
        name="Observability",
        path="platform/observability",
        web_url="https://gitlab.example.com/platform/observability",
    ),
    ("project", "4021"): GitLabTarget(
        id="4021",
        type="project",
        name="Developer Experience",
        path="platform/developer-experience",
        web_url="https://gitlab.example.com/platform/developer-experience",
    ),
    ("project", "9090"): GitLabTarget(
        id="9090",
        type="project",
        name="Archive Maintenance",
        path="platform/archive-maintenance",
        web_url="https://gitlab.example.com/platform/archive-maintenance",
    ),
    ("group", "7"): GitLabTarget(
        id="7",
        type="group",
        name="Platform Engineering",
        path="platform",
        web_url="https://gitlab.example.com/groups/platform",
    ),
}

project_merge_requests: dict[str, list[GitLabMergeRequest]] = {
    "1042": [
        GitLabMergeRequest(
            id=1001,
            iid=18,
            project_id=1042,
            project_path="platform/payments",
            title="Reduce settlement latency for batch payouts",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/18",
            state="opened",
            draft=False,
            author=people["ava"],
            reviewers=[people["noah"]],
            created_at="2026-05-01T09:10:00.000Z",
            updated_at="2026-05-02T11:00:00.000Z",
            merged_at=None,
            changes_count=184,
        ),
        GitLabMergeRequest(
            id=1002,
            iid=17,
            project_id=1042,
            project_path="platform/payments",
            title="Ship reserve reconciliation summary export",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/17",
            state="merged",
            draft=False,
            author=people["marcus"],
            reviewers=[people["noah"], people["lena"]],
            created_at="2026-05-03T09:00:00.000Z",
            updated_at="2026-05-05T18:15:00.000Z",
            merged_at="2026-05-05T18:15:00.000Z",
            changes_count=426,
        ),
        GitLabMergeRequest(
            id=1003,
            iid=16,
            project_id=1042,
            project_path="platform/payments",
            title="Refactor ledger write path for region failover",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/16",
            state="merged",
            draft=False,
            author=people["lena"],
            reviewers=[people["iris"]],
            created_at="2026-04-24T08:10:00.000Z",
            updated_at="2026-05-01T19:30:00.000Z",
            merged_at="2026-05-01T19:30:00.000Z",
            changes_count=1124,
        ),
        GitLabMergeRequest(
            id=1004,
            iid=15,
            project_id=1042,
            project_path="platform/payments",
            title="Add weekly treasury exposure digest",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/15",
            state="opened",
            draft=False,
            author=people["iris"],
            reviewers=[],
            created_at="2026-05-06T10:20:00.000Z",
            updated_at="2026-05-08T10:20:00.000Z",
            merged_at=None,
            changes_count=94,
        ),
        GitLabMergeRequest(
            id=1005,
            iid=14,
            project_id=1042,
            project_path="platform/payments",
            title="Stabilize duplicate payment detection rules",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/14",
            state="merged",
            draft=False,
            author=people["ava"],
            reviewers=[people["jude"]],
            created_at="2026-04-03T08:50:00.000Z",
            updated_at="2026-04-08T15:45:00.000Z",
            merged_at="2026-04-08T15:45:00.000Z",
            changes_count=310,
        ),
        GitLabMergeRequest(
            id=1006,
            iid=13,
            project_id=1042,
            project_path="platform/payments",
            title="Draft invoice annotation service boundary",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/13",
            state="opened",
            draft=True,
            author=people["noah"],
            reviewers=[people["lena"]],
            created_at="2026-05-07T12:15:00.000Z",
            updated_at="2026-05-09T09:05:00.000Z",
            merged_at=None,
            changes_count=68,
        ),
        GitLabMergeRequest(
            id=1007,
            iid=12,
            project_id=1042,
            project_path="platform/payments",
            title="Backfill payout trace identifiers",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/12",
            state="closed",
            draft=False,
            author=people["jude"],
            reviewers=[people["noah"]],
            created_at="2026-04-27T16:30:00.000Z",
            updated_at="2026-05-04T11:00:00.000Z",
            merged_at=None,
            changes_count=156,
        ),
        GitLabMergeRequest(
            id=1008,
            iid=11,
            project_id=1042,
            project_path="platform/payments",
            title="Tune settlement retries for PSP timeouts",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/11",
            state="merged",
            draft=False,
            author=people["ava"],
            reviewers=[people["noah"], people["iris"]],
            created_at="2026-05-02T07:05:00.000Z",
            updated_at="2026-05-03T16:10:00.000Z",
            merged_at="2026-05-03T16:10:00.000Z",
            changes_count=212,
        ),
        GitLabMergeRequest(
            id=1009,
            iid=10,
            project_id=1042,
            project_path="platform/payments",
            title="Migrate partner reconciliation mappings",
            web_url="https://gitlab.example.com/platform/payments/-/merge_requests/10",
            state="opened",
            draft=False,
            author=people["marcus"],
            reviewers=[people["iris"]],
            created_at="2026-04-28T13:00:00.000Z",
            updated_at="2026-04-29T13:00:00.000Z",
            merged_at=None,
            changes_count=980,
        ),
    ],
    "4021": [
        GitLabMergeRequest(
            id=2006,
            iid=22,
            project_id=4021,
            project_path="platform/developer-experience",
            title="Retire legacy bootstrap templates",
            web_url="https://gitlab.example.com/platform/developer-experience/-/merge_requests/22",
            state="opened",
            draft=False,
            author=people["jude"],
            reviewers=[people["lena"]],
            created_at="2026-04-26T07:45:00.000Z",
            updated_at="2026-04-28T07:45:00.000Z",
            merged_at=None,
            changes_count=905,
        ),
        GitLabMergeRequest(
            id=2008,
            iid=16,
            project_id=4021,
            project_path="platform/developer-experience",
            title="Reduce preview environment lead time",
            web_url="https://gitlab.example.com/platform/developer-experience/-/merge_requests/16",
            state="merged",
            draft=False,
            author=people["lena"],
            reviewers=[people["noah"], people["iris"]],
            created_at="2026-05-04T08:30:00.000Z",
            updated_at="2026-05-06T11:45:00.000Z",
            merged_at="2026-05-06T11:45:00.000Z",
            changes_count=298,
        ),
        GitLabMergeRequest(
            id=2010,
            iid=14,
            project_id=4021,
            project_path="platform/developer-experience",
            title="Standardize ephemeral environment labels",
            web_url="https://gitlab.example.com/platform/developer-experience/-/merge_requests/14",
            state="opened",
            draft=False,
            author=people["iris"],
            reviewers=[],
            created_at="2026-05-08T10:15:00.000Z",
            updated_at="2026-05-09T16:20:00.000Z",
            merged_at=None,
            changes_count=132,
        ),
    ],
    "9090": [],
}

group_merge_requests: dict[str, list[GitLabMergeRequest]] = {
    "7": [
        project_merge_requests["1042"][1],
        project_merge_requests["1042"][5],
        project_merge_requests["1042"][7],
        GitLabMergeRequest(
            id=2002,
            iid=32,
            project_id=2044,
            project_path="platform/identity",
            title="Harden SSO tenant bootstrap telemetry",
            web_url="https://gitlab.example.com/platform/identity/-/merge_requests/32",
            state="opened",
            draft=False,
            author=people["lena"],
            reviewers=[people["jude"]],
            created_at="2026-05-01T13:00:00.000Z",
            updated_at="2026-05-01T13:00:00.000Z",
            merged_at=None,
            changes_count=402,
        ),
        GitLabMergeRequest(
            id=2003,
            iid=27,
            project_id=3055,
            project_path="platform/observability",
            title="Unify trace sampling and SLO annotations",
            web_url="https://gitlab.example.com/platform/observability/-/merge_requests/27",
            state="merged",
            draft=False,
            author=people["noah"],
            reviewers=[people["iris"]],
            created_at="2026-04-20T09:30:00.000Z",
            updated_at="2026-05-02T17:40:00.000Z",
            merged_at="2026-05-02T17:40:00.000Z",
            changes_count=1180,
        ),
        GitLabMergeRequest(
            id=2004,
            iid=26,
            project_id=2044,
            project_path="platform/identity",
            title="Introduce reviewer load balancing hints",
            web_url="https://gitlab.example.com/platform/identity/-/merge_requests/26",
            state="opened",
            draft=False,
            author=people["iris"],
            reviewers=[],
            created_at="2026-05-07T11:20:00.000Z",
            updated_at="2026-05-08T18:00:00.000Z",
            merged_at=None,
            changes_count=87,
        ),
        GitLabMergeRequest(
            id=2005,
            iid=24,
            project_id=3055,
            project_path="platform/observability",
            title="Refine error budget drilldown cards",
            web_url="https://gitlab.example.com/platform/observability/-/merge_requests/24",
            state="merged",
            draft=False,
            author=people["marcus"],
            reviewers=[people["jude"], people["noah"]],
            created_at="2026-04-29T08:00:00.000Z",
            updated_at="2026-05-01T12:10:00.000Z",
            merged_at="2026-05-01T12:10:00.000Z",
            changes_count=344,
        ),
        project_merge_requests["4021"][0],
        project_merge_requests["4021"][1],
    ],
}


def get_fixture_target(target_type: str, target_id: str) -> GitLabTarget:
    try:
        return fixture_targets[(target_type, target_id)]
    except KeyError as exc:
        raise NotFoundError("The GitLab target was not found.") from exc


def get_fixture_merge_requests(target_type: str, target_id: str, limit: int) -> list[GitLabMergeRequest]:
    if target_type == "project":
        merge_requests = project_merge_requests.get(target_id)
    else:
        merge_requests = group_merge_requests.get(target_id)

    if merge_requests is None:
        raise NotFoundError("The GitLab target was not found.")

    return [clone_merge_request(merge_request) for merge_request in merge_requests[:limit]]


def clone_merge_request(merge_request: GitLabMergeRequest) -> GitLabMergeRequest:
    return GitLabMergeRequest(
        id=merge_request.id,
        iid=merge_request.iid,
        project_id=merge_request.project_id,
        project_path=merge_request.project_path,
        title=merge_request.title,
        web_url=merge_request.web_url,
        state=merge_request.state,
        draft=merge_request.draft,
        author=GitLabPerson(
            id=merge_request.author.id,
            name=merge_request.author.name,
            username=merge_request.author.username,
            web_url=merge_request.author.web_url,
        ),
        reviewers=[
            GitLabPerson(
                id=reviewer.id,
                name=reviewer.name,
                username=reviewer.username,
                web_url=reviewer.web_url,
            )
            for reviewer in merge_request.reviewers
        ],
        created_at=merge_request.created_at,
        updated_at=merge_request.updated_at,
        merged_at=merge_request.merged_at,
        changes_count=merge_request.changes_count,
    )
